language: objective-c
cache: cocoapods

install:
- gem install xcpretty cocoapods slather -N
- pod install

script:
- set -o pipefail && xcodebuild test -workspace Cortado.xcworkspace -scheme Cortado -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c

after_success: slather